# Generated by Django 3.2.6 on 2021-08-29 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prdname', models.CharField(max_length=100)),
                ('prddesc', models.TextField()),
                ('prdprice', models.DecimalField(decimal_places=2, max_digits=5)),
                ('prdcost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('prdcreated', models.DateTimeField()),
            ],
        ),
    ]
