# Generated by Django 3.2.6 on 2021-08-29 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prdcost',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Product Cost'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prdcreated',
            field=models.DateTimeField(verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prddesc',
            field=models.TextField(verbose_name='Product Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prdname',
            field=models.CharField(max_length=100, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prdprice',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Product Price'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prdiProductImage', models.ImageField(upload_to='product/', verbose_name='Image')),
                ('prdiproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Product')),
            ],
        ),
    ]
