# Generated by Django 3.2.6 on 2021-08-30 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_category_catparent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterField(
            model_name='category',
            name='catdesc',
            field=models.TextField(verbose_name='Category Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='catimg',
            field=models.ImageField(upload_to='category/', verbose_name='Category Image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='catname',
            field=models.CharField(max_length=50, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='catparent',
            field=models.ForeignKey(blank=True, limit_choices_to={'catparent__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='Category Parent'),
        ),
        migrations.CreateModel(
            name='Product_Alternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palnalternatives', models.ManyToManyField(related_name='alternative_produts', to='product.Product', verbose_name='')),
                ('palnproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_product', to='product.product', verbose_name='')),
            ],
            options={
                'verbose_name': 'Product Alternative',
                'verbose_name_plural': 'Product Alternatives',
            },
        ),
    ]
