# Generated by Django 3.2.6 on 2021-08-30 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20210830_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_alternative',
            name='palnalternatives',
            field=models.ManyToManyField(related_name='alternative_produts', to='product.Product', verbose_name='Alternatives'),
        ),
        migrations.AlterField(
            model_name='product_alternative',
            name='palnproduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_product', to='product.product', verbose_name='Product'),
        ),
        migrations.CreateModel(
            name='Product_Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paccalternatives', models.ManyToManyField(related_name='accessories_products', to='product.Product', verbose_name='Accessories')),
                ('paccproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mainAccessory_product', to='product.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Accessory',
                'verbose_name_plural': 'Product Accessories',
            },
        ),
    ]
