# Generated by Django 3.2.6 on 2021-09-01 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20210831_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prdslug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
