# Generated by Django 3.2.6 on 2021-09-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_prdslug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prddisprice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Discount Price'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='prdslug',
            field=models.SlugField(blank=True, null=True, verbose_name='Slug'),
        ),
    ]
