# Generated by Django 3.2.6 on 2021-09-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20210904_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prdisnew',
            field=models.BooleanField(default=True, verbose_name='New Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prdslug',
            field=models.SlugField(blank=True, null=True, verbose_name='Product URL'),
        ),
    ]
